global:
  ros__parameters:
    topic_prefix: '/fb'


antenna_split:
  ros__parameters:
    name: 'split'
    #input_topic: '/fix'
    gps_topic: '/fix'
    #output_topics: ['/gps/front', '/gps/back']
    gps_front: '/gps/front'
    gps_back: '/gps/back'
    kallman_type: 0

antenna_fuse:
  ros__parameters:
    name: 'fuse'
    #input_topics: ['/gps/front', '/gps/back']
    gps_front: '/gps/front'
    gps_back: '/gps/back'

gps_to_enu:
  ros__parameters:
    name: 'gps_to_enu'

odom_n_path:
  ros__parameters:
    name: 'odometry'

transform_pub:
  ros__parameters:
    name: 'transform_pub'