global:
  ros__parameters:
    topic_prefix: '/fb'

antenna_split:
  ros__parameters:
    name: 'split'
    #input_topic:
    gps_topic: '/gps'
    #output_topics:
    gps_main: '/gps_main'
    gps_aux: '/gps_aux'
    kallman_type: 1

antenna_fuse:
  ros__parameters:
    name: 'fuse'
    #input_topics:
    gps_main: '/gps_main'
    gps_aux: '/gps_aux'
    angle_gpses: 0.0

gps_to_enu:
  ros__parameters:
    name: 'gps_to_enu'

odom_n_path:
  ros__parameters:
    name: 'odometry'

transform_pub:
  ros__parameters:
    name: 'transform_pub'